FROM node:20-alpine AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG EXPO_PUBLIC_API_URL_DEV
ARG EXPO_PUBLIC_TELEGRAM_BOT_USERNAME
ENV EXPO_PUBLIC_API_URL_DEV=${EXPO_PUBLIC_API_URL_DEV}
ENV EXPO_PUBLIC_TELEGRAM_BOT_USERNAME=${EXPO_PUBLIC_TELEGRAM_BOT_USERNAME}

RUN npm run build:web

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
