import type { ServiceAccessItem } from '@/utils/servicesService';

export type CatalogServiceItem = ServiceAccessItem;

export const SERVICE_CATALOG: CatalogServiceItem[] = [
  {
    id: 1,
    key: 'qrcodes',
    name: 'QR генератор и аналитика',
    kind: 'CLOUD',
    route: '/services/qrcodes',
    icon: 'qr-code-outline',
    description: 'Создание QR-кодов, печать и аналитика по сканам.',
    gradientStart: '#5B21B6',
    gradientEnd: '#7C3AED',
    visible: true,
    enabled: true,
  },
  {
    id: 2,
    key: 'appeals',
    name: 'Обращения',
    kind: 'CLOUD',
    route: '/services/appeals',
    icon: 'documents',
    description: 'Центр общения с клиентами и партнёрами.',
    gradientStart: '#a8d5ba',
    gradientEnd: '#4cad50',
    visible: true,
    enabled: true,
  },
  {
    id: 3,
    key: 'tracking',
    name: 'Геомаршруты',
    kind: 'CLOUD',
    route: '/services/tracking',
    icon: 'map-outline',
    description: 'Маршруты, точки и контроль передвижений.',
    gradientStart: '#ffd89b',
    gradientEnd: '#19547b',
    visible: true,
    enabled: true,
  },
  {
    id: 4,
    key: 'tasks',
    name: 'Задачи',
    kind: 'CLOUD',
    route: '/tasks',
    icon: 'list-outline',
    description: 'Постановка и контроль задач команды.',
    gradientStart: '#90caf9',
    gradientEnd: '#2196f3',
    visible: true,
    enabled: false,
  },
  {
    id: 5,
    key: 'reports',
    name: 'Отчёты',
    kind: 'CLOUD',
    route: '/reports',
    icon: 'stats-chart-outline',
    description: 'Визуальные отчёты и показатели.',
    gradientStart: '#ce93d8',
    gradientEnd: '#9c27b0',
    visible: true,
    enabled: false,
  },
  {
    id: 6,
    key: 'clients',
    name: 'Клиенты',
    kind: 'CLOUD',
    route: '/clients',
    icon: 'people-outline',
    description: 'Управление клиентской базой.',
    gradientStart: '#ef9a9a',
    gradientEnd: '#f44336',
    visible: true,
    enabled: false,
  },
];

