import { Platform, StyleSheet } from 'react-native';

export function createUsersTabStyles(colors: any) {
  return StyleSheet.create({
    root: { flex: 1, gap: 8 },
    rootMobile: { gap: 0 },
    toolbar: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      padding: 12,
      gap: 8,
      backgroundColor: colors.cardBackground,
    },
    toolbarCompact: {
      paddingHorizontal: 8,
      paddingTop: 6,
      paddingBottom: 5,
      gap: 5,
      borderWidth: 0,
      borderRadius: 0,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    toolbarTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
    },
    toolbarTopRowCompact: {
      alignItems: 'center',
      gap: 5,
    },
    toolbarSearchCol: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    toolbarSearchInput: {
      height: 48,
      backgroundColor: colors.inputBackground,
    },
    toolbarSearchInputCompact: {
      height: 42,
    },
    toolbarMeta: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    toolbarMetaCompact: {
      marginTop: 2,
      gap: 6,
    },
    toolbarMetaText: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: '700',
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    toolbarMetaTextCompact: {
      fontSize: 10,
      paddingHorizontal: 7,
      paddingVertical: 4,
    },
    filtersWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      alignItems: 'flex-start',
    },
    filterGroupCol: {
      flexGrow: 0,
      flexBasis: 330,
      minWidth: 220,
      gap: 6,
    },
    filterGroupLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '700',
    },
    filtersIconBtn: {
      width: 44,
      minWidth: 44,
      height: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filtersIconBtnCompact: {
      width: 34,
      minWidth: 34,
      height: 34,
      borderRadius: 9,
    },
    filtersIconBtnActive: {
      backgroundColor: `${colors.tint}22`,
    },
    resetFiltersBtn: {
      minHeight: 44,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    resetFiltersBtnDisabled: {
      opacity: 0.5,
    },
    resetFiltersBtnText: {
      color: colors.tint,
      fontSize: 12,
      fontWeight: '700',
    },
    filterResetButton: {
      alignSelf: 'flex-end',
      minWidth: 120,
      marginTop: 18,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 7,
      color: colors.text,
      backgroundColor: colors.inputBackground,
      ...(Platform.OS === 'web'
        ? ({
            outlineStyle: 'none',
            outlineWidth: 0,
          } as any)
        : null),
    },
    chips: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    chip: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    chipActive: { borderColor: colors.tint, backgroundColor: `${colors.tint}15` },
    chipText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    chipTextActive: { color: colors.tint },
    desktop: { flex: 1, flexDirection: 'row', gap: 12 },
    list: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      overflow: 'hidden',
    },
    listHeader: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    listHeaderText: { color: colors.secondaryText, fontWeight: '700', fontSize: 12 },
    side: {
      width: 360,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 10,
    },
    rowWrap: { paddingHorizontal: 8, paddingTop: 8 },
    rowWrapFlat: { paddingHorizontal: 0, paddingTop: 0 },
    paperUserCard: {
      borderColor: colors.inputBorder,
      backgroundColor: colors.background,
      borderRadius: 10,
    },
    paperUserCardSelected: {
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}08`,
    },
    paperUserCardFlat: {
      borderWidth: 0,
      borderRadius: 0,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    paperUserCardInner: {
      padding: 10,
      gap: 7,
    },
    paperUserCardInnerFlat: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 6,
    },
    flatUserItem: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    flatUserMain: {
      minHeight: 78,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      paddingLeft: 12,
      paddingRight: 4,
      paddingVertical: 9,
    },
    flatUserAvatar: {
      width: 42,
      height: 42,
      position: 'relative',
      flexShrink: 0,
    },
    flatUserInfo: { flex: 1, minWidth: 0, gap: 2 },
    flatUserTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    flatUserId: { color: colors.secondaryText, fontSize: 10, fontWeight: '700' },
    flatUserBadges: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 2 },
    flatUserBadgeText: { fontSize: 10, fontWeight: '800' },
    flatUserEditButton: { width: 40, height: 40, margin: 0, flexShrink: 0 },
    flatUserModeration: {
      paddingHorizontal: 12,
      paddingBottom: 9,
    },
    paperChip: {
      height: 24,
      borderWidth: 1,
    },
    row: {
      padding: 8,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      backgroundColor: colors.background,
    },
    rowSelected: { borderColor: colors.tint, backgroundColor: `${colors.tint}08` },
    rowHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    rowId: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowTime: { color: colors.secondaryText, fontSize: 10, fontWeight: '700' },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, alignItems: 'center' },
    tag: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 6,
      paddingVertical: 3,
      backgroundColor: colors.inputBackground,
      borderColor: colors.inputBorder,
    },
    tagText: { color: colors.text, fontSize: 10, fontWeight: '700' },
    summaryRow: { flexDirection: 'row', gap: 10, alignItems: 'center' },
    avatarWrap: { width: 44, height: 44, position: 'relative', borderRadius: 22, overflow: 'visible' },
    avatar: { width: 26, height: 26, borderRadius: 13 },
    avatarFallback: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.tint,
    },
    avatarFallbackText: { color: '#FFFFFF', fontWeight: '800', fontSize: 9 },
    onlineDot: {
      position: 'absolute',
      right: -1,
      top: -1,
      width: 7,
      height: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.background,
      backgroundColor: '#94A3B8',
    },
    rowMainTextWrap: { flex: 1, minWidth: 0 },
    rowName: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowNameMeta: { color: colors.secondaryText, fontWeight: '700', fontSize: 10 },
    rowMetaLine: { color: colors.secondaryText, fontSize: 11 },
    badge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    badgeText: { fontSize: 11, fontWeight: '800' },
    badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
    metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    metaCell: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    metaLabel: { color: colors.secondaryText, fontSize: 9, fontWeight: '700' },
    metaValue: { color: colors.text, fontSize: 11, fontWeight: '700' },
    channelsText: { color: colors.secondaryText, fontSize: 11 },
    actions: { flexDirection: 'row', gap: 5, flexWrap: 'wrap', alignItems: 'center' },
    actionHint: { color: colors.secondaryText, fontSize: 10, fontWeight: '600' },
    btn: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 4,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 72,
    },
    btnText: { color: colors.text, fontWeight: '700', fontSize: 10 },
    pagination: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    paginationText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    loadMoreInlineIndicator: {
      marginTop: 8,
      marginBottom: 10,
    },
    empty: { color: colors.secondaryText, fontSize: 13, textAlign: 'center', paddingVertical: 22 },
    mobileList: { flexGrow: 1 },
    mobileCard: {
      borderRadius: 0,
      overflow: 'hidden',
    },
    modalWrap: {
      flex: 1,
      backgroundColor: 'rgba(2,6,23,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 12,
    },
    modalCard: {
      width: '100%',
      maxWidth: 760,
      maxHeight: '90%',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 8,
    },
    filtersModalCard: {
      maxWidth: 620,
      maxHeight: '84%',
      gap: 10,
    },
    filtersModalScroll: {
      width: '100%',
      maxHeight: 420,
    },
    filtersModalContent: {
      gap: 10,
      paddingBottom: 4,
    },
    filtersModalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    filtersModalResetBtn: {
      minHeight: 36,
      paddingHorizontal: 10,
      borderRadius: 9,
      backgroundColor: 'transparent',
      borderColor: colors.inputBorder,
    },
    modalPrimaryBtn: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: colors.tint,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalPrimaryBtnText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '700',
    },
    userEditorModalCard: {
      width: '100%',
      maxWidth: 980,
      flex: 1,
      minHeight: 0,
      maxHeight: Platform.OS === 'web' ? ('86vh' as any) : '100%',
      padding: 0,
      gap: 0,
      overflow: 'hidden',
      backgroundColor: colors.cardBackground,
      borderRadius: Platform.OS === 'web' ? 16 : 0,
    },
    filtersFullscreen: { flex: 1, minHeight: 0 },
    filtersFullscreenHeader: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingLeft: 16,
      paddingRight: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
    },
    filtersFullscreenFooter: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 8,
      paddingHorizontal: 12,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.inputBorder,
    },
    userEditorFullscreen: {
      flex: 1,
      minHeight: 0,
    },
    userEditorLoading: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    userEditorPaperDialog: {
      width: '92%',
      maxWidth: 980,
      maxHeight: '88vh' as any,
      alignSelf: 'center',
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      overflow: 'hidden',
    },
    userEditorHeader: {
      minHeight: 58,
      paddingHorizontal: Platform.OS === 'web' ? 18 : 12,
      paddingVertical: Platform.OS === 'web' ? 14 : 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    userEditorHeaderText: { flex: 1, minWidth: 0, gap: 2 },
    userEditorScroll: {
      flex: 1,
      minHeight: 0,
      maxHeight: Platform.OS === 'web' ? ('70vh' as any) : undefined,
      backgroundColor: colors.cardBackground,
    },
    userEditorContent: {
      paddingHorizontal: Platform.OS === 'web' ? 16 : 10,
      paddingTop: 10,
      paddingBottom: 20,
      gap: 10,
    },
    userEditorSection: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      paddingHorizontal: Platform.OS === 'web' ? 12 : 2,
      paddingTop: 4,
      paddingBottom: 14,
      gap: 9,
    },
    userEditorSectionTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    userEditorGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    userEditorField: {
      minWidth: 220,
      flexBasis: 280,
      flexGrow: 1,
      flexShrink: 1,
      gap: 6,
    },
    userEditorLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '700',
    },
    userEditorMuted: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: '600',
    },
    userEditorReadonly: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 10,
      backgroundColor: colors.inputBackground,
    },
    userEditorReadonlyText: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '600',
    },
    userProfileGrid: {
      gap: 8,
    },
    userProfileCard: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      backgroundColor: colors.cardBackground,
      padding: 10,
      gap: 8,
    },
    userProfileCardDisabled: {
      opacity: 0.75,
      backgroundColor: colors.inputBackground,
    },
    userProfileCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    userProfileName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    userProfileBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    userProfileBadgeExists: {
      borderColor: '#86EFAC',
      backgroundColor: '#DCFCE7',
    },
    userProfileBadgeMissing: {
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    userProfileBadgeText: {
      fontSize: 10,
      fontWeight: '800',
    },
    userProfileBadgeTextExists: {
      color: '#166534',
    },
    userProfileBadgeTextMissing: {
      color: colors.secondaryText,
    },
    userEditorFooter: {
      borderTopWidth: 1,
      borderTopColor: colors.inputBorder,
      minHeight: 62,
      paddingHorizontal: 12,
      paddingTop: 9,
      paddingBottom: 10,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
      backgroundColor: colors.inputBackground,
    },
    userEditorSaveButtonMobile: {
      flex: 1,
      minHeight: 46,
      justifyContent: 'center',
    },
    userEditorSaveBtn: {
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
    },
    userEditorSaveText: {
      color: colors.tint,
    },
    sectionTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
    sub: { color: colors.secondaryText, fontSize: 12 },
    hidden: {
      display: 'none',
    },
  });
}
