export const MOBILE_SHEET_MAX_WIDTH = 420;
export const MOBILE_SHEET_SIDE_INSET = 12;
export const MOBILE_SHEET_COLLAPSED_HEIGHT = 92;
export const MOBILE_SHEET_MIN_EXPANDED_HEIGHT = 320;
export const MOBILE_SHEET_MAX_HEIGHT_RATIO = 0.92;
export const MOBILE_SHEET_TOP_RESERVED = 148;
export const MOBILE_SHEET_BOTTOM_GAP = 2;
export const MOBILE_SHEET_BODY_MIN_HEIGHT = 220;
