import { Platform, StyleSheet } from 'react-native';

const webPressable = Platform.OS === 'web' ? ({ cursor: 'pointer', userSelect: 'none' } as const) : null;

export const mobileSheetStyles = StyleSheet.create({
  overlayWrap: {
    position: 'absolute',
    zIndex: 4,
  },
  shell: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.93)',
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.12)',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  header: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15, 23, 42, 0.06)',
  },
  handle: {
    alignSelf: 'center',
    width: 28,
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.75)',
    marginBottom: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerMain: {
    flex: 1,
    minWidth: 0,
    ...(webPressable ?? {}),
  },
  headerTextStack: {
    gap: 2,
    marginTop: 3,
  },
  title: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 19,
  },
  meta: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  currentText: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 15,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  toggleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.5)',
    backgroundColor: 'rgba(239, 246, 255, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    ...(webPressable ?? {}),
  },
  toggleBtnActive: {
    borderColor: '#60A5FA',
    backgroundColor: 'rgba(219, 234, 254, 0.92)',
  },
  body: {
    minHeight: 0,
    overflow: 'hidden',
  },
  contentRoot: {
    flex: 1,
    minHeight: 0,
  },
  toolbarSection: {
    flexShrink: 0,
    paddingTop: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  mobileToolbarRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 2,
    paddingBottom: 6,
  },
  mobileToolbarLeft: {
    width: 42,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  mobileToolbarFilterWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  mobileToolbarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  mobileActionButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: '#D7DEE8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    ...(webPressable ?? {}),
  },
  mobileActionButtonPrimary: {
    borderColor: '#93C5FD',
    backgroundColor: '#2563EB',
  },
  mobileActionButtonSuccess: {
    borderColor: '#16A34A',
    backgroundColor: '#16A34A',
  },
  mobileActionButtonWarning: {
    borderColor: '#F97316',
    backgroundColor: '#F97316',
  },
  mobileActionButtonDisabled: {
    opacity: 0.5,
  },
  mobileActionButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
    marginHorizontal: 12,
    marginBottom: 4,
  },
  scroll: {
    flex: 1,
    minHeight: 0,
    height: '100%',
  },
  scrollContent: {
    gap: 6,
    paddingTop: 0,
    paddingLeft: 4,
    paddingRight: 4,
    paddingBottom: 20,
  },
  statusNoticeText: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '700',
    backgroundColor: 'rgba(248, 250, 252, 0.9)',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  routeListEndSpacer: {
    height: 4,
  },
  loadMoreIndicator: {
    marginTop: 4,
    marginBottom: 2,
  },
});
