import { Platform, StyleSheet } from 'react-native';

export type AdminStyles = ReturnType<typeof createAdminStyles>;

export const createAdminStyles = (colors: any) =>
  StyleSheet.create({
    screen: { flex: 1 },
    container: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 6,
      paddingBottom: 14,
      gap: 10,
      width: '100%',
      ...Platform.select({
        web: { maxWidth: 1440, alignSelf: 'center', width: '100%', paddingHorizontal: 32, paddingTop: 14 },
        default: {},
      }),
    },
    title: { fontSize: 22, fontWeight: '800', color: colors.text, marginBottom: 10 },
    tabsWrap: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      padding: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    tabsScroll: { flexGrow: 0 },
    tabsContent: { flexDirection: 'row', gap: 8, paddingBottom: 2 },
    tabBtn: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    tabBtnActive: {
      backgroundColor: colors.tint + '12',
      borderColor: colors.tint,
    },
    tabText: { color: colors.secondaryText, fontWeight: '700' },
    tabTextActive: { color: colors.tint },
    panel: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      padding: 14,
      gap: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
      flex: 1,
      minHeight: 0,
    },
    sectionTitle: { fontSize: 16, fontWeight: '800', color: colors.text },
    updateGrid: { gap: 12, width: '100%' },
    updateGridWide: { flexDirection: 'row', alignItems: 'flex-start' },
    updateColumn: { flex: 1, gap: 12, width: '100%' },
    updateColumnStack: { marginTop: 12 },
    updateCard: {
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      gap: 10,
      width: '100%',
    },
    updateHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    segmentGroup: { flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
    fieldRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, alignItems: 'flex-start' },
    fieldBlock: { flex: 1, minWidth: 160, gap: 6 },
    labelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
    labelText: { fontWeight: '700', color: colors.text },
    labelHint: { color: colors.secondaryText, fontSize: 12 },
    helpBtn: { padding: 2 },
    updateRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
    segment: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    segmentActive: {
      borderColor: colors.tint,
      backgroundColor: colors.tint + '12',
    },
    segmentText: { fontWeight: '700', color: colors.secondaryText },
    segmentTextActive: { color: colors.tint },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 4,
    },
    toggleRowInline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    toggleLabel: { fontWeight: '700', color: colors.text },
    toggleLabelSmall: { fontSize: 12, fontWeight: '700', color: colors.secondaryText },
    linkBtn: { paddingHorizontal: 8, paddingVertical: 6 },
    linkBtnText: { color: colors.tint, fontWeight: '700' },
    updateItemRow: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 8,
    },
    updateItemTitle: { fontWeight: '700', color: colors.text },
    updateActions: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    tagPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    tagText: { fontSize: 11, fontWeight: '700', color: colors.secondaryText },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.inputBackground,
      borderColor: colors.inputBorder,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    searchInput: { flex: 1, color: colors.text },
    searchRowCompact: {
      paddingHorizontal: 10,
      paddingVertical: 0,
      height: 36,
    },
    summaryWrap: { paddingHorizontal: 0 },
    summaryRow: { flexDirection: 'row', gap: 8, paddingBottom: 4 },
    summaryRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingBottom: 4 },
    summaryCard: {
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      minWidth: 96,
      gap: 4,
      overflow: 'hidden',
    },
    summaryValue: { fontSize: 16, fontWeight: '800', color: colors.text },
    summaryLabel: { fontSize: 11, fontWeight: '700', color: colors.secondaryText },
    split: { flex: 1, flexDirection: 'row', gap: 12 },
    toolbarCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      gap: 10,
    },
    toolbarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    toolbarActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexShrink: 0,
    },
    filterAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    filterIconBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterActionActive: {
      borderColor: colors.tint,
      backgroundColor: colors.tint + '12',
    },
    filterActionText: { fontWeight: '700', color: colors.text },
    filterBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      paddingHorizontal: 4,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.tint,
    },
    filterBadgeText: { color: '#fff', fontSize: 11, fontWeight: '800' },
    usersBody: { flex: 1, minHeight: 0, gap: 12 },
    usersBodyWide: {
      flexDirection: 'row',
      alignItems: 'stretch',
      ...Platform.select({
        web: { gap: 16 },
        default: {},
      }),
    },
    filtersColumn: { width: 320, minWidth: 260, flexShrink: 0 },
    filtersCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      gap: 10,
    },
    filtersModalCard: {
      width: '92%',
      maxWidth: 520,
      maxHeight: '72%',
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    filtersModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    filtersModalTitle: { fontSize: 16, fontWeight: '800', color: colors.text },
    filtersModalClose: { paddingHorizontal: 10, paddingVertical: 6 },
    filtersModalCloseText: { color: colors.tint, fontWeight: '700' },
    userListWrap: {
      flex: 1,
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      borderWidth: 0,
      overflow: 'visible',
    },
    userColumnWrap: { gap: 8, paddingHorizontal: 0, paddingBottom: 8 },
    userFilters: {
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
      gap: 8,
      backgroundColor: colors.cardBackground,
    },
    filterGrid: { gap: 8 },
    filterGridWide: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    filterGroup: {
      gap: 4,
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      flexGrow: 1,
      minWidth: 180,
    },
    filterGroupFull: {
      width: '100%',
      minWidth: 0,
      flexGrow: 0,
    },
    filterGroupHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    filterLabel: { fontSize: 11, fontWeight: '800', color: colors.text },
    filterChipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingVertical: 2, paddingRight: 0 },
    filterChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    filterChipCompact: { paddingHorizontal: 8, paddingVertical: 5 },
    filterChipActive: {
      borderColor: colors.tint,
      backgroundColor: colors.tint + '12',
    },
    filterChipHover: { backgroundColor: colors.tint + '10', borderColor: colors.tint },
    filterChipText: { fontSize: 11, fontWeight: '700', color: colors.secondaryText },
    filterChipTextActive: { color: colors.tint },
    sortDirBtn: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    sortDirText: { fontSize: 11, fontWeight: '800', color: colors.text },
    filterGroupCompactRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      paddingHorizontal: 4,
    },
    resetBtn: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    resetBtnText: { fontSize: 11, fontWeight: '800', color: colors.secondaryText },
    filterHint: { fontSize: 11, color: colors.secondaryText, fontWeight: '600' },
    userItem: {
      padding: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.inputBorder,
    },
    userItemActive: { backgroundColor: colors.tint + '22' },
    userItemTitle: { fontWeight: '700', color: colors.text },
    userItemTitleActive: { color: colors.tint },
    userItemSub: { color: colors.secondaryText, fontSize: 13 },
    userItemSubActive: { color: colors.tint },
    userCardWrap: { paddingHorizontal: 0 },
    userCardWrapWide: { flex: 1, paddingHorizontal: 0 },
    userCard: {
      padding: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.inputBackground,
      gap: 8,
      marginBottom: 8,
    },
    userCardActive: { backgroundColor: colors.tint + '12' },
    userCardBlocked: { backgroundColor: '#FEF2F2' },
    userCardHover: {
      borderColor: colors.tint,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    userRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
    userAvatarWrap: { position: 'relative' },
    userAvatar: { width: 40, height: 40, borderRadius: 12 },
    userAvatarFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.inputBorder },
    userAvatarText: { fontSize: 14, fontWeight: '800', color: colors.text },
    userPresenceDot: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.cardBackground,
    },
    userInfo: { flex: 1, minWidth: 0, gap: 4 },
    userNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    userName: { fontSize: 14, fontWeight: '800', color: colors.text, flex: 1 },
    userIdBadge: {
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    userIdText: { fontSize: 10, fontWeight: '800', color: colors.secondaryText },
    userMeta: {
      fontSize: 11,
      color: colors.secondaryText,
      flexShrink: 1,
      flexWrap: 'wrap',
      minWidth: 0,
      flex: 1,
      alignSelf: 'stretch',
    },
    userMetaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, flexWrap: 'wrap' },
    userMetaStrong: { fontSize: 11, fontWeight: '800', color: colors.text },
    userPillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    statusPill: {
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 999,
      borderWidth: 1,
    },
    statusPillText: { fontSize: 10, fontWeight: '800' },
    rolePill: {
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    rolePillText: { fontSize: 10, fontWeight: '800', color: colors.secondaryText },
    departmentPill: {
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    departmentPillText: { fontSize: 10, fontWeight: '800', color: colors.text },
    userPresenceRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    userPresenceDotSmall: { width: 8, height: 8, borderRadius: 4 },
    userPresenceText: { fontSize: 11, color: colors.secondaryText },
    subtitle: { color: colors.secondaryText },
    notice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    noticeSuccess: { backgroundColor: '#DCFCE7', borderColor: '#86EFAC' },
    noticeError: { backgroundColor: '#FEE2E2', borderColor: '#FCA5A5' },
    noticeInfo: { backgroundColor: '#E0F2FE', borderColor: '#7DD3FC' },
    noticeText: { flex: 1, fontWeight: '600', color: colors.text },
    noticeTextSuccess: { color: '#166534' },
    noticeTextError: { color: '#991B1B' },
    noticeClose: { padding: 4 },
    progressCard: {
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      gap: 8,
    },
    progressCardSuccess: { borderColor: '#86EFAC', backgroundColor: '#F0FDF4' },
    progressCardError: { borderColor: '#FCA5A5', backgroundColor: '#FEF2F2' },
    progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    progressHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    progressTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    progressTitle: { fontWeight: '800', color: colors.text },
    progressPercent: { fontWeight: '700', color: colors.secondaryText },
    progressBar: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.inputBackground,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.tint,
    },
    progressMessage: { color: colors.secondaryText },
    progressSteps: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    progressStep: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
    },
    progressStepDone: { borderColor: colors.tint, backgroundColor: colors.tint + '12' },
    progressStepActive: { borderColor: colors.tint, backgroundColor: colors.tint + '22' },
    progressStepText: { fontSize: 11, fontWeight: '700', color: colors.secondaryText },
    progressStepTextDone: { color: colors.text },
    progressStepTextActive: { color: colors.text },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 12,
    },
    modalCard: {
      width: '100%',
      maxWidth: 920,
      borderRadius: 20,
      padding: 14,
      backgroundColor: colors.cardBackground,
    },
    modalBody: { flex: 1, minHeight: 0 },
    modalScroll: { flex: 1, minHeight: 0 },
    modalScrollContent: { paddingBottom: 16 },
    modalTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
    modalClose: {
      marginTop: 8,
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: 'center',
      borderColor: colors.inputBorder,
    },
    modalCloseText: { fontSize: 16, fontWeight: '700', color: colors.text },
    center: { alignItems: 'center', justifyContent: 'center', padding: 20 },

    heroWrap: {
      borderRadius: 20,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#E0E7FF',
      marginBottom: 16,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    heroBg: { ...StyleSheet.absoluteFillObject },
    heroInner: { padding: 18 },
    avatarOuter: {
      alignSelf: 'flex-start',
      width: 96,
      height: 96,
      borderRadius: 28,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#EEF2FF',
      marginBottom: 10,
    },
    avatar: { width: 88, height: 88, borderRadius: 24 },
    avatarFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF2FF' },
    avatarInitials: { fontSize: 28, fontWeight: '800', color: '#0F172A' },
    heroTitle: { fontSize: 22, fontWeight: '800', color: '#0F172A' },
    heroSubtitle: { marginTop: 6, color: '#334155' },
    chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },

    chip: {
      flexDirection: 'row',
      gap: 6,
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
    },
    chipText: { fontSize: 12, fontWeight: '700' },

    cardsWrap: { gap: 12 },
    infoCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 5,
      elevation: 2,
    },
    infoIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: '#EEF2FF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoLabel: { color: '#6B7280', fontSize: 12, fontWeight: '700' },
    infoValue: { color: '#111827', fontSize: 14, fontWeight: '700' },
    infoInput: { color: '#111827', fontSize: 14, fontWeight: '700', padding: 0 },
    optionChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      marginRight: 8,
      marginTop: 6,
      backgroundColor: '#F9FAFB',
    },
    optionChipActive: {
      backgroundColor: '#DBEAFE',
      borderColor: '#93C5FD',
    },
    optionText: { color: '#111827', fontWeight: '700' },
    optionTextActive: { color: '#1D4ED8' },
    pickerOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pickerCard: {
      width: '90%',
      maxWidth: 420,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 4,
    },
    pickerTitle: { fontSize: 16, fontWeight: '800', color: colors.text, marginBottom: 10 },
    pickerOption: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      marginBottom: 8,
    },
    pickerOptionActive: { borderColor: '#6366F1', backgroundColor: '#EEF2FF' },
    pickerOptionText: { color: colors.text, fontWeight: '700' },
    pickerOptionTextActive: { color: '#4338CA' },
    profileTabsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    profileTabCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      minWidth: 160,
    },
    profileTabCardActive: {
      borderColor: colors.tint,
      backgroundColor: colors.tint + '12',
    },
    profileTabCardDisabled: { opacity: 0.55 },
    profileAvatar: { width: 42, height: 42, borderRadius: 14 },
    profileAvatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.inputBorder,
    },
    profileAvatarText: { fontSize: 14, fontWeight: '800', color: colors.text },
    profileTabMeta: { flex: 1, minWidth: 0 },
    profileTabLabel: { fontSize: 14, fontWeight: '800', color: colors.text },
    profileTabStatus: { fontSize: 12, color: colors.secondaryText, marginTop: 2 },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderColor: colors.inputBorder,
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: colors.text,
    },
    smallBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    itemRow: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    iconBtn: {
      width: 34,
      height: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.inputBackground,
    },
    iconBtnDanger: {
      width: 34,
      height: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#F87171',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FEF2F2',
    },
    nameText: {
      flex: 1,
      color: colors.text,
      fontWeight: '700',
      flexShrink: 1,
    },
    nameInputFlex: {
      flex: 1,
      minWidth: 0,
    },
    permRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      marginBottom: 8,
    },
    permRowActive: {
      borderColor: colors.tint,
      backgroundColor: colors.tint + '12',
    },
    permText: { flex: 1, color: colors.secondaryText, fontWeight: '700' },
    permTextActive: { color: colors.text },
    deptUserCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      padding: 12,
      marginBottom: 8,
      gap: 4,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    deptUserCardPressed: { backgroundColor: colors.tint + '12', borderColor: colors.tint },
    deptUserHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    deptUserName: { flex: 1, fontWeight: '700', color: colors.text, marginRight: 8 },
    deptUserRole: { color: colors.secondaryText, fontWeight: '700' },
    deptUserSub: { color: colors.secondaryText },
  });
