import { StyleSheet } from 'react-native';

export function createUsersTabStyles(colors: any) {
  return StyleSheet.create({
    root: { flex: 1, gap: 8 },
    toolbar: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      padding: 10,
      gap: 8,
      backgroundColor: colors.cardBackground,
    },
    toolbarCompact: {
      padding: 6,
      gap: 4,
    },
    toolbarTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
    },
    toolbarTopRowCompact: {
      alignItems: 'center',
      gap: 5,
    },
    toolbarSearchCol: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    toolbarSearchInput: {
      minHeight: 44,
      borderRadius: 10,
      paddingVertical: 10,
    },
    toolbarSearchInputCompact: {
      minHeight: 34,
      borderRadius: 9,
      paddingVertical: 6,
    },
    toolbarMeta: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    toolbarMetaCompact: {
      marginTop: 2,
      gap: 6,
    },
    toolbarMetaText: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: '700',
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    toolbarMetaTextCompact: {
      fontSize: 10,
      paddingHorizontal: 7,
      paddingVertical: 4,
    },
    filtersWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    filterGroupCol: {
      flexGrow: 1,
      flexBasis: 240,
      minWidth: 220,
      gap: 6,
    },
    filterGroupLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '700',
    },
    filtersIconBtn: {
      width: 44,
      minWidth: 44,
      height: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filtersIconBtnCompact: {
      width: 34,
      minWidth: 34,
      height: 34,
      borderRadius: 9,
    },
    filtersIconBtnActive: {
      backgroundColor: `${colors.tint}22`,
    },
    resetFiltersBtn: {
      minHeight: 44,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    resetFiltersBtnDisabled: {
      opacity: 0.5,
    },
    resetFiltersBtnText: {
      color: colors.tint,
      fontSize: 12,
      fontWeight: '700',
    },
    input: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 7,
      color: colors.text,
      backgroundColor: colors.inputBackground,
    },
    chips: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    chip: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    chipActive: { borderColor: colors.tint, backgroundColor: `${colors.tint}15` },
    chipText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    chipTextActive: { color: colors.tint },
    desktop: { flex: 1, flexDirection: 'row', gap: 12 },
    list: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      overflow: 'hidden',
    },
    listHeader: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    listHeaderText: { color: colors.secondaryText, fontWeight: '700', fontSize: 12 },
    side: {
      width: 360,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 10,
    },
    rowWrap: { paddingHorizontal: 6, paddingTop: 6 },
    row: {
      padding: 8,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      backgroundColor: colors.background,
    },
    rowSelected: { borderColor: colors.tint, backgroundColor: `${colors.tint}08` },
    rowHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    rowId: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowTime: { color: colors.secondaryText, fontSize: 10, fontWeight: '700' },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, alignItems: 'center' },
    tag: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 6,
      paddingVertical: 3,
      backgroundColor: colors.inputBackground,
      borderColor: colors.inputBorder,
    },
    tagText: { color: colors.text, fontSize: 10, fontWeight: '700' },
    summaryRow: { flexDirection: 'row', gap: 6, alignItems: 'center' },
    avatarWrap: { width: 26, height: 26, position: 'relative' },
    avatar: { width: 26, height: 26, borderRadius: 13 },
    avatarFallback: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.tint,
    },
    avatarFallbackText: { color: '#FFFFFF', fontWeight: '800', fontSize: 9 },
    onlineDot: {
      position: 'absolute',
      right: -1,
      top: -1,
      width: 7,
      height: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.background,
      backgroundColor: '#94A3B8',
    },
    rowMainTextWrap: { flex: 1, minWidth: 0 },
    rowName: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowNameMeta: { color: colors.secondaryText, fontWeight: '700', fontSize: 10 },
    rowMetaLine: { color: colors.secondaryText, fontSize: 11 },
    badge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    badgeText: { fontSize: 11, fontWeight: '800' },
    badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
    metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    metaCell: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    metaLabel: { color: colors.secondaryText, fontSize: 9, fontWeight: '700' },
    metaValue: { color: colors.text, fontSize: 11, fontWeight: '700' },
    channelsText: { color: colors.secondaryText, fontSize: 11 },
    actions: { flexDirection: 'row', gap: 5, flexWrap: 'wrap', alignItems: 'center' },
    actionHint: { color: colors.secondaryText, fontSize: 10, fontWeight: '600' },
    btn: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 4,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 72,
    },
    btnText: { color: colors.text, fontWeight: '700', fontSize: 10 },
    pagination: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    paginationText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    loadMoreInlineIndicator: {
      marginTop: 8,
      marginBottom: 10,
    },
    empty: { color: colors.secondaryText, fontSize: 13, textAlign: 'center', paddingVertical: 22 },
    mobileList: { gap: 6 },
    mobileCard: {
      borderRadius: 12,
      overflow: 'hidden',
    },
    modalWrap: {
      flex: 1,
      backgroundColor: 'rgba(2,6,23,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 12,
    },
    modalCard: {
      width: '100%',
      maxWidth: 760,
      maxHeight: '90%',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 8,
    },
    filtersModalCard: {
      maxWidth: 620,
      maxHeight: '84%',
      gap: 10,
    },
    filtersModalScroll: {
      width: '100%',
      maxHeight: 420,
    },
    filtersModalContent: {
      gap: 10,
      paddingBottom: 4,
    },
    filtersModalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    filtersModalResetBtn: {
      minHeight: 36,
      paddingHorizontal: 10,
      borderRadius: 9,
      backgroundColor: 'transparent',
      borderColor: colors.inputBorder,
    },
    modalPrimaryBtn: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.tint,
      backgroundColor: colors.tint,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalPrimaryBtnText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '700',
    },
    userEditorModalCard: {
      maxWidth: 980,
      padding: 0,
      gap: 0,
      overflow: 'hidden',
    },
    userEditorHeader: {
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 14,
      gap: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    userEditorScroll: {
      flex: 1,
    },
    userEditorContent: {
      padding: 16,
      gap: 12,
    },
    userEditorSection: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.background,
      padding: 12,
      gap: 8,
    },
    userEditorSectionTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    userEditorGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    userEditorField: {
      minWidth: 240,
      flexGrow: 1,
      flexShrink: 1,
      gap: 6,
    },
    userEditorLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '700',
    },
    userEditorMuted: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: '600',
    },
    userEditorReadonly: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 10,
      backgroundColor: colors.inputBackground,
    },
    userEditorReadonlyText: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: '600',
    },
    userProfileGrid: {
      gap: 8,
    },
    userProfileCard: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      backgroundColor: colors.cardBackground,
      padding: 10,
      gap: 8,
    },
    userProfileCardDisabled: {
      opacity: 0.75,
      backgroundColor: colors.inputBackground,
    },
    userProfileCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    userProfileName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    userProfileBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    userProfileBadgeExists: {
      borderColor: '#86EFAC',
      backgroundColor: '#DCFCE7',
    },
    userProfileBadgeMissing: {
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    userProfileBadgeText: {
      fontSize: 10,
      fontWeight: '800',
    },
    userProfileBadgeTextExists: {
      color: '#166534',
    },
    userProfileBadgeTextMissing: {
      color: colors.secondaryText,
    },
    userEditorFooter: {
      borderTopWidth: 1,
      borderTopColor: colors.inputBorder,
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
      backgroundColor: colors.inputBackground,
    },
    userEditorSaveBtn: {
      borderColor: colors.tint,
      backgroundColor: `${colors.tint}14`,
    },
    userEditorSaveText: {
      color: colors.tint,
    },
    sectionTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
    sub: { color: colors.secondaryText, fontSize: 12 },
    hidden: {
      display: 'none',
    },
  });
}
