import { StyleSheet } from 'react-native';

export function createUsersTabStyles(colors: any) {
  return StyleSheet.create({
    root: { flex: 1, gap: 8 },
    toolbar: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      padding: 10,
      gap: 8,
      backgroundColor: colors.cardBackground,
    },
    toolbarMeta: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    toolbarMetaText: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: '700',
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 7,
      color: colors.text,
      backgroundColor: colors.inputBackground,
    },
    chips: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    chip: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    chipActive: { borderColor: colors.tint, backgroundColor: `${colors.tint}15` },
    chipText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    chipTextActive: { color: colors.tint },
    desktop: { flex: 1, flexDirection: 'row', gap: 12 },
    list: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      overflow: 'hidden',
    },
    listHeader: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
    },
    listHeaderText: { color: colors.secondaryText, fontWeight: '700', fontSize: 12 },
    side: {
      width: 360,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 10,
    },
    rowWrap: { paddingHorizontal: 6, paddingTop: 6 },
    row: {
      padding: 8,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      backgroundColor: colors.background,
    },
    rowSelected: { borderColor: colors.tint, backgroundColor: `${colors.tint}08` },
    rowHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    rowId: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowTime: { color: colors.secondaryText, fontSize: 10, fontWeight: '700' },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, alignItems: 'center' },
    tag: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 6,
      paddingVertical: 3,
      backgroundColor: colors.inputBackground,
      borderColor: colors.inputBorder,
    },
    tagText: { color: colors.text, fontSize: 10, fontWeight: '700' },
    summaryRow: { flexDirection: 'row', gap: 6, alignItems: 'center' },
    avatarWrap: { width: 26, height: 26, position: 'relative' },
    avatar: { width: 26, height: 26, borderRadius: 13 },
    avatarFallback: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.tint,
    },
    avatarFallbackText: { color: '#FFFFFF', fontWeight: '800', fontSize: 9 },
    onlineDot: {
      position: 'absolute',
      right: -1,
      top: -1,
      width: 7,
      height: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.background,
      backgroundColor: '#94A3B8',
    },
    rowMainTextWrap: { flex: 1, minWidth: 0 },
    rowName: { color: colors.text, fontWeight: '800', fontSize: 13 },
    rowNameMeta: { color: colors.secondaryText, fontWeight: '700', fontSize: 10 },
    rowMetaLine: { color: colors.secondaryText, fontSize: 11 },
    badge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    badgeText: { fontSize: 11, fontWeight: '800' },
    badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
    metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    metaCell: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 5,
      backgroundColor: colors.inputBackground,
    },
    metaLabel: { color: colors.secondaryText, fontSize: 9, fontWeight: '700' },
    metaValue: { color: colors.text, fontSize: 11, fontWeight: '700' },
    channelsText: { color: colors.secondaryText, fontSize: 11 },
    actions: { flexDirection: 'row', gap: 5, flexWrap: 'wrap', alignItems: 'center' },
    actionHint: { color: colors.secondaryText, fontSize: 10, fontWeight: '600' },
    btn: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 4,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 72,
    },
    btnText: { color: colors.text, fontWeight: '700', fontSize: 10 },
    pagination: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    paginationText: { color: colors.secondaryText, fontSize: 11, fontWeight: '700' },
    empty: { color: colors.secondaryText, fontSize: 13, textAlign: 'center', paddingVertical: 22 },
    mobileList: { gap: 6 },
    mobileCard: {
      borderRadius: 12,
      overflow: 'hidden',
    },
    modalWrap: {
      flex: 1,
      backgroundColor: 'rgba(2,6,23,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 12,
    },
    modalCard: {
      width: '100%',
      maxWidth: 760,
      maxHeight: '90%',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.cardBackground,
      padding: 12,
      gap: 8,
    },
    sectionTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
    sub: { color: colors.secondaryText, fontSize: 12 },
  });
}
