export const WEB_SIDEBAR_BREAKPOINT = 820;

export const DESKTOP_SPLIT_MIN_CONTENT_WIDTH = 1020;
export const DESKTOP_SPLIT_HYSTERESIS = 24;
export const DESKTOP_SPLIT_ENTER_WIDTH = DESKTOP_SPLIT_MIN_CONTENT_WIDTH + DESKTOP_SPLIT_HYSTERESIS;
export const DESKTOP_SPLIT_EXIT_WIDTH = DESKTOP_SPLIT_MIN_CONTENT_WIDTH - DESKTOP_SPLIT_HYSTERESIS;
export const DESKTOP_SIDE_PADDING = 16;
export const DESKTOP_GAP = 8;
export const DESKTOP_LEFT_PAGE_INSET = 12;

export const DESKTOP_INBOX_MIN_WIDTH = 320;
export const DESKTOP_INBOX_PREFERRED_WIDTH = 400;
export const DESKTOP_INBOX_MAX_WIDTH = 440;

export const DESKTOP_CHAT_MIN_WIDTH = 560;
export const DESKTOP_CHAT_PREFERRED_WIDTH = 920;
export const DESKTOP_CHAT_MAX_WIDTH = 1280;
